# Generated by Django 4.0.5 on 2022-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=350)),
                ('availability', models.BooleanField(null=True)),
                ('needing_repair', models.BooleanField(null=True)),
                ('durability', models.IntegerField(null=True)),
                ('max_durability', models.IntegerField(null=True)),
                ('mileage', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('minimum_rent_period', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
